services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    tty: true
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - ./api:/app
    depends_on:
      - db
    command: ["sleep", "infinity"]

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "dev_app"

volumes:
  db-volume:
