version: "3.7"
services:
    app:
      build: .
      tty: true
      ports:
        - 3000:3000
      volumes:
        - ./:/app
        - /app/node_modules
      depends_on:
        - db
    db:
      image: postgres:16.2
      ports: 
        - 5432:5432
      volumes:
        - db-volume:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: 'user'
        POSTGRES_PASSWORD: 'postgres'

volumes:
  db-volume: