services:
  front:
    build:
      context: .
      dockerfile: ./.devcontainer/front/Dockerfile
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./front:/app

  api:
    build:
      context: .
      dockerfile: ./.devcontainer/api/Dockerfile
    tty: true
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - ./api:/app
    depends_on:
      - db

  db:
    image: postgres:16.2
    ports: 
      - 5432:5432
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'postgres'

  terraform:
    build:
      context: .
      dockerfile: ./terraform/Dockerfile
    volumes:
      - ~/.aws:/root/.aws:ro
      - ./terraform:/workspaces

volumes:
  db-volume: