version: "3.7"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.app
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./app/:/app

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    tty: true
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - ./server/:/app
    depends_on:
      - db

  db:
    image: postgres:16.2
    ports: 
      - 5432:5432
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'postgres'

volumes:
  db-volume: