type Task {
  id: Int!
  name: String
  detail: String
}

type Habit {
  id: Int!
  note: String
  tasks: [Task]
}

type Query {
  task(id: Int!): Task
  tasks: [Task]
  habit(id: Int!): Habit
}

type Mutation {
  createTask(name: String! detail: String): Task
}