name: Docker Image Push
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: AWS Configure Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
      - run: aws s3 ls s3://test-uchihara
